"""Epistemology Bacon mode — Baconian Inductivism via tables of instances.

The Bacon mode's distinctive process is *eliminative*: it compiles systematic
evidence tables (Presence, Absence, Degrees) for a phenomenon, then eliminates
non-essential factors by cross-table comparison to induce the Form — the
essential nature.  The method is that of Francis Bacon's Novum Organum (1620):
true knowledge comes from systematic observation and elimination, not
speculation.  Ideas emerge from the induced Form, not from brainstorming.
"""

from __future__ import annotations

from datetime import date
from typing import Any

from tulla.core.phase import Phase, PhaseContext

from ._helpers import parse_epistemology_output
from .models import EpistemologyOutput

_FRAMEWORKS = ["Table of Presence", "Table of Absence", "Table of Degrees"]
_OUTPUT_FILE = "ep-bacon-ideas.md"


class BaconPhase(Phase[EpistemologyOutput]):
    """Epistemology Bacon mode: compile evidence tables, eliminate, induce the Form, generate."""

    phase_id: str = "ep-bacon"
    timeout_s: float = 900.0

    def build_prompt(self, ctx: PhaseContext) -> str:
        output_file = ctx.work_dir / _OUTPUT_FILE
        run_date = date.today().isoformat()

        return (
            f"You are Epistemology Ralph — Bacon Mode for idea {ctx.idea_id}.\n"
            "\n"
            "Your reasoning is grounded in Francis Bacon's tradition: true\n"
            "knowledge comes from systematic observation and elimination, not\n"
            "speculation. Your method is drawn from Novum Organum (1620) — it\n"
            "requires compiling evidence tables then eliminating non-essential\n"
            "factors to induce the Form (the essential nature of a phenomenon).\n"
            "You are an empiricist, not a theorist. Tables come first; ideas\n"
            "come from what the tables reveal after elimination.\n"
            "\n"
            "## Operational Rules\n"
            "\n"
            "You must obey these 7 constraints throughout:\n"
            "\n"
            "1. IDENTIFY THE PHENOMENON. Before anything else, distill the\n"
            "   idea into a single, observable phenomenon — something whose\n"
            "   presence, absence, and variation can be concretely investigated.\n"
            "   If the idea is too abstract, ground it until it is observable.\n"
            "2. TABLE OF PRESENCE. Compile at least 5 concrete, named instances\n"
            "   where the phenomenon is clearly present. Each instance must be\n"
            "   specific and real — a named technology, product, event, or case.\n"
            "   Do not use vague or hypothetical examples.\n"
            "3. TABLE OF ABSENCE. Compile at least 5 similar cases where the\n"
            "   phenomenon would be expected but is absent. These must be close\n"
            "   analogues of the Presence cases — similar in kind, context, or\n"
            "   domain — yet the phenomenon does not appear. This is the hardest\n"
            "   table: 'similar cases where the phenomenon is absent' is NOT\n"
            "   'cases where the opposite is true'.\n"
            "4. TABLE OF DEGREES. Compile at least 5 cases where the phenomenon\n"
            "   appears with varying intensity — from faint to strong. Each case\n"
            "   must specify what varies and in what direction. Use concrete,\n"
            "   named instances.\n"
            "5. ELIMINATE VIA CROSS-TABLE COMPARISON. Compare across all three\n"
            "   tables. Any factor present in both Presence AND Absence cases\n"
            "   cannot be the essential nature (it does not track the phenomenon).\n"
            "   Any factor that does not vary with the Degrees table cannot\n"
            "   explain variation. Systematically eliminate non-essential factors.\n"
            "6. INDUCE THE FORM. From what survives elimination, state the Form\n"
            "   as a concise principle — the essential nature of the phenomenon.\n"
            "   The Form must be SURPRISING — it cannot merely restate the\n"
            "   original phenomenon in different words.\n"
            "7. GENERATE IDEAS FROM THE INDUCED FORM. Ideas must flow from the\n"
            "   Form, not from the phenomenon directly. The Form is the\n"
            "   generative engine — it reveals what the phenomenon truly IS,\n"
            "   and ideas exploit that deeper understanding.\n"
            "\n"
            "## Phase 1: The Phenomenon\n"
            "\n"
            f"1. Read idea {ctx.idea_id}: mcp__ontology-server__get_idea\n"
            "2. Query the pool for context: mcp__ontology-server__query_ideas\n"
            "3. Distill the idea into a single observable phenomenon — something\n"
            "   concrete whose presence, absence, and variation can be investigated.\n"
            "\n"
            "## Phase 2: Table of Presence\n"
            "\n"
            "4. Compile at least 5 concrete, named instances where the phenomenon\n"
            "   is clearly present. For each, describe what makes the phenomenon\n"
            "   manifest and what surrounding conditions exist.\n"
            "\n"
            "## Phase 3: Table of Absence\n"
            "\n"
            "5. Compile at least 5 similar cases where the phenomenon would be\n"
            "   expected but is absent. Each must be a close analogue of a\n"
            "   Presence case — similar domain, context, or kind — yet the\n"
            "   phenomenon does not appear. For each, describe what conditions\n"
            "   differ from the corresponding Presence case.\n"
            "\n"
            "## Phase 4: Table of Degrees\n"
            "\n"
            "6. Compile at least 5 cases where the phenomenon varies in intensity.\n"
            "   Order from weakest to strongest manifestation. For each, identify\n"
            "   what co-varies with the intensity change.\n"
            "\n"
            "## Phase 5: Elimination\n"
            "\n"
            "7. Cross-compare all three tables. Systematically eliminate factors\n"
            "   that cannot be the Form:\n"
            "   - Present in BOTH Presence and Absence → not essential\n"
            "   - Does not co-vary with Degrees → not explanatory\n"
            "   List each eliminated factor and WHY it was eliminated.\n"
            "\n"
            "## Phase 6: The Form\n"
            "\n"
            "8. State the Form — the essential nature of the phenomenon — as a\n"
            "   concise principle. It must survive all eliminations and explain\n"
            "   the pattern across all three tables.\n"
            "\n"
            "## Phase 7: Idea Generation\n"
            "\n"
            "Generate exactly 3 ideas from the induced Form. Each must exploit\n"
            "the Form's insight — not merely riff on the original phenomenon.\n"
            "For each, tag with the table that most informed it:\n"
            "\n"
            "**Table of Presence**: An idea that extends or applies the Form\n"
            "to new domains — where else should this essential nature manifest?\n"
            "\n"
            "**Table of Absence**: An idea that exploits the absence — what\n"
            "becomes possible in the spaces where the phenomenon is missing\n"
            "but the Form predicts it should exist?\n"
            "\n"
            "**Table of Degrees**: An idea that exploits variation — how can\n"
            "the Form be amplified, attenuated, or tuned to create something\n"
            "new?\n"
            "\n"
            "## Phase 8: Save and Report\n"
            "\n"
            "For each generated idea, save it:\n"
            '  mcp__ontology-server__create_idea with author "AI",\n'
            '  tags ["epi-ralph", "bacon", "<table-name-lowercase>"]\n'
            "\n"
            f"Write the full report to: {output_file}\n"
            "\n"
            "Format:\n"
            "\n"
            "# Generated Ideas — Bacon Mode\n"
            f"**Root Idea**: {ctx.idea_id}\n"
            f"**Date**: {run_date}\n"
            f"**Frameworks**: {', '.join(_FRAMEWORKS)}\n"
            "\n"
            "## The Phenomenon\n"
            "**Observable Phenomenon**: {the single concrete phenomenon}\n"
            "**Source**: idea {id}\n"
            "\n"
            "## Table of Presence\n"
            "| # | Instance | Phenomenon Manifestation | Surrounding Conditions |\n"
            "|---|----------|--------------------------|------------------------|\n"
            "| 1 | {named instance} | {how it manifests} | {conditions} |\n"
            "| 2 | ... | ... | ... |\n"
            "{at least 5 rows}\n"
            "\n"
            "## Table of Absence\n"
            "| # | Similar Case | Why Expected | Why Absent | Differs From |\n"
            "|---|-------------|-------------|------------|---------------|\n"
            "| 1 | {named case} | {why expected} | {why absent} | {Presence case #} |\n"
            "| 2 | ... | ... | ... | ... |\n"
            "{at least 5 rows}\n"
            "\n"
            "## Table of Degrees\n"
            "| # | Instance | Intensity | Co-varying Factor |\n"
            "|---|----------|-----------|--------------------|\n"
            "| 1 | {named instance, weakest} | {low/medium/high} | {what co-varies} |\n"
            "| 2 | ... | ... | ... |\n"
            "{at least 5 rows, ordered weakest to strongest}\n"
            "\n"
            "## Elimination\n"
            "**Eliminated factors**:\n"
            "- {factor}: eliminated because {present in both "
            "Presence and Absence / does not co-vary "
            "with Degrees}\n"
            "{list all eliminated factors}\n"
            "\n"
            "## The Form\n"
            "**Induced Form**: {the essential nature, as a concise principle}\n"
            "**Why Surprising**: {why this is not a restatement of the phenomenon}\n"
            "**Surviving Evidence**: {how the Form explains all three tables}\n"
            "\n"
            "## Idea 1: {Title}\n"
            "**Framework**: Table of Presence\n"
            "**Form Applied**: {how the Form generates this idea}\n"
            "**Description**: {2-3 sentences}\n"
            "\n"
            "## Idea 2: {Title}\n"
            "**Framework**: Table of Absence\n"
            "**Form Applied**: {how the Form generates this idea}\n"
            "**Description**: {2-3 sentences}\n"
            "\n"
            "## Idea 3: {Title}\n"
            "**Framework**: Table of Degrees\n"
            "**Form Applied**: {how the Form generates this idea}\n"
            "**Description**: {2-3 sentences}\n"
            "\n"
            "## Anti-Collapse Guards\n"
            "\n"
            "Tables must lead to ELIMINATION, not mere description. If your\n"
            "tables are just lists of examples without cross-comparison and\n"
            "systematic elimination, you are doing survey work, not Baconian\n"
            "induction.\n"
            "\n"
            "If your Table of Absence contains cases where the OPPOSITE is true\n"
            "rather than similar cases where the phenomenon is ABSENT, you are\n"
            "doing generic comparison, not Baconian induction. Absence means:\n"
            "close analogues where you would EXPECT the phenomenon but it does\n"
            "not appear.\n"
            "\n"
            "Do NOT skip the Absence table. It is the hardest table and the\n"
            "most important for elimination. Without it, you cannot distinguish\n"
            "essential from accidental features.\n"
            "\n"
            "Do NOT list vague or hypothetical instances. Every entry in every\n"
            "table must be a concrete, named, real case. 'A company that might\n"
            "do X' is not an instance. Name the company.\n"
            "\n"
            "Do NOT produce a Form that just restates the original phenomenon.\n"
            "If your phenomenon is 'successful open-source projects' and your\n"
            "Form is 'projects that are open-source and successful', you have\n"
            "not induced — you have tautologized. The Form must be SURPRISING.\n"
            "\n"
            "The Form must be SURPRISING. It reveals the essential nature that\n"
            "was not obvious before the tables and elimination. If the Form\n"
            "is what anyone would say without doing the analysis, your\n"
            "elimination was too shallow.\n"
        )

    def get_tools(self, ctx: PhaseContext) -> list[dict[str, Any]]:
        return [
            {"name": "mcp__ontology-server__get_idea"},
            {"name": "mcp__ontology-server__query_ideas"},
            {"name": "mcp__ontology-server__create_idea"},
            {"name": "Write"},
        ]

    def parse_output(self, ctx: PhaseContext, raw: Any) -> EpistemologyOutput:
        return parse_epistemology_output(
            self.phase_id, "bacon", ctx, raw, _OUTPUT_FILE, _FRAMEWORKS,
        )
